# Generated by Django 5.1.1 on 2024-09-22 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название', max_length=250, verbose_name='Название')),
                ('product_model', models.CharField(help_text='Укажите модель продукта', max_length=250, verbose_name='Модель')),
                ('create_date', models.DateTimeField(help_text='Укажите дату выхода продукта на рынок', verbose_name='Дата выхода на рынок')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
