# Generated by Django 5.1.1 on 2024-09-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateField(help_text='Укажите дату выхода продукта на рынок', verbose_name='Дата выхода на рынок'),
        ),
    ]
