# Generated by Django 5.1.1 on 2024-09-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название', max_length=250, verbose_name='Название')),
                ('email', models.EmailField(help_text='Укажите адрес электронной почты', max_length=254, unique=True, verbose_name='Почта')),
                ('country', models.CharField(help_text='Укажите страну', max_length=50, verbose_name='Страна')),
                ('city', models.CharField(help_text='Укажите город', max_length=50, verbose_name='Город')),
                ('street', models.CharField(help_text='Укажите улицу', max_length=50, verbose_name='Улица')),
                ('number_home', models.CharField(help_text='Укажите номер дома', max_length=10, verbose_name='Номер дома')),
                ('level_company', models.IntegerField(default=0, verbose_name='Уровень компании')),
                ('type_company', models.CharField(choices=[('individual', 'индивидуальный'), ('factory', 'завод'), ('retail', 'розничный')], max_length=20, verbose_name='Тип компании')),
                ('supplier_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название поставщика')),
                ('supplier_id', models.IntegerField(blank=True, null=True, verbose_name='Идентификатор поставщика')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_supplier', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название компании-поставщика')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Долг')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('company_customer', models.IntegerField(verbose_name='Компания покупатель')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
    ]
