# Generated by Django 5.1.1 on 2024-09-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Укажите название', max_length=250, unique=True, verbose_name='Название'),
        ),
    ]
